apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  serviceAccountName: aws-node
  automountServiceAccountToken: true
  containers:
  - name: alpine
    image: alpine:3.11
    command: [ "sleep", "1000"]